### ISSUE TITLE
HTML / REACT ELEMENTS

### ISSUE THREAD

**Issue by SklyerX** [maxeth/react-type-animation#12]
how can I make it type out HTML elements? I want to change the color of (for example) the first two letters to black and the next two to red.

**Comment by maxeth** [comment]
I believe you could change the styles of entire words/strings by changing the wrappers ```className``` or ```style``` attribute via React ```state``` with callbackFunctions, but single words won't work currently, because the package only compares and manipulates text inside one specific DOM node (no child nodes, which would be required).

I agree that this would indeed be a great feature, but it would require completely fundamental changes to the code. I may look into this and see if I'd be able to find an easier solution to achieve what you described in the near future.

**Comment by SklyerX** [comment]
I see thanks!
