### ISSUE TITLE
Callbacks in a sequence is executed even if component is removed before the sequence is finished

### ISSUE THREAD

**Issue by rangelojc** [maxeth/react-type-animation#59]
Say we have a long series of text that has a callback after, rendered conditionally.

```jsx
showMe ? <TypeAnimation
    sequence={[
      someSuperLongText,
      () => console.log("foobar"),
    ]}
  /> : <></>
```

"foobar" is logged regardless if `showMe` is suddenly toggled to `false` between the animation. Is this intended? 

Is there a workaround to this?

**Comment by maxeth** [comment]
Hey,

this package was initially just a React wrapper for typical.js, so the logic responsible for the typing animation is a simple, recursive function that modifies the DOM in classic vanilla JS style.

Now, when the component unmounts, the recursive function seems to continue running in the background. **I don't think we can do anything against this for now**. To properly handle cleanups with component unmounts and allow for dynamic rendering of the component with dynamic props etc., this package would have to be rewritten to the React-way of using `useEffect` instead of explicit recursion. I'd gladly do this in the near future but I'm highly limited in time.

To address this, the component, for now, is permanently memoized and never meant to be unmounted or re-rendered. So for now, any kind of dynamic usage may be problematic, even though I'm not sure what you're trying to do here. 

See https://react-type-animation.netlify.app/#immutability

 Hence, I was always sceptical of re-rendering techniques like https://github.com/maxeth/react-type-animation/issues/27 due to the potential memory leaks and unexpected behavior of the recursive functions continuing to run in the background as in your case.

**Comment by rangelojc** [comment]
Sounds good. It's a minor issue overall. TY for the response.

Decent workaround! Closing this for now.
