### ISSUE TITLE
Issue with streaming dynamic content.

### ISSUE THREAD

**Issue by NickolasBenakis** [maxeth/react-type-animation#62]
Hello amazing people 👋

This package totally rocks 🚀
But I am facing a struggle with dynamic content. 

My use case is that I am iterating through a streamable string value and I am updating react state on each string append action.

render 1 // "hello"
render 2 // "hello friends"
render 3 // "hello friends this is Nikos"

...
Even though I pass the content like this below 👇 as long as the string is getting longer I am not getting any typing animation or updates to the text. 
It feels like the library needs the full finished string instead of having the string change on demand.

Is there any workaround solution? Thank you

```
   <TypeAnimationWrapper
      sequence={[content]}
      wrapper="span"
      speed={75}
   />

```
The below typing animation effect is what I am looking for 👇 (I used raw HTML divs for the example and it works)

https://github.com/user-attachments/assets/93798ad6-45f3-461f-be9c-1e9d41d29cd5

**Comment by maxeth** [comment]
Hi,

> It feels like the library needs the full finished string instead of having the string change on demand.

Yes, that's right, check https://react-type-animation.netlify.app/#immutability

At the moment you can't (safely) dynamically append text because the animation is handled via a recursive function and not via React state, and there's no mechanism implemented yet to cleanup the recursive function on component unmount. By allowing re-renders the component would cause A) serious memory leaks since with each re-render a new recursive function would be spawned and B) animation bugs since there would now be multiple animations modifying the same element passed via `ref`.

I'm aware that this is a major limitation and probably makes this package unsuitable for something like an AI Chatbot that streams responses, but instead of looking for hacky temporary solutions for now, I'd prefer rewriting the package from ground up to be declarative the React-way via `useEffect` and without recursion at some point.

The most dynamic usage possible at the moment is something like this https://github.com/maxeth/react-type-animation/issues/27, which allows for changing the `sequence`/rendering out a new text (but with a final string sequence already in place, that's a must). But appending individual pieces won't work smoothly for now.

**Comment by NickolasBenakis** [comment]
wow, Thank you @maxeth for the detailed response. I would be more than happy to help you with rewriting this if you plan for it, let me know 👍 For my case I will use a custom approach for now.👌✅
